<?php
session_start();
include 'connection.php'; 
require 'vendor/autoload.php'; 

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

if ($_SERVER['REQUEST_METHOD'] == 'POST') {
    $first_name = mysqli_real_escape_string($conn, $_POST['first_name']);
    $last_name = mysqli_real_escape_string($conn, $_POST['last_name']);
    $email = mysqli_real_escape_string($conn, $_POST['email']);
    $contact = mysqli_real_escape_string($conn, $_POST['contact']);

    // Generate a random 10-character password
    $password = bin2hex(random_bytes(5)); // 10-character password
    $hashed_password = password_hash($password, PASSWORD_DEFAULT);

    // Check if email already exists in any of the tables
    $email_check_query = "SELECT email FROM (
                            SELECT email FROM admin
                            UNION ALL
                            SELECT email FROM employees
                            UNION ALL
                            SELECT email FROM customers
                          ) AS users
                          WHERE email = '$email' LIMIT 1";

    $result = $conn->query($email_check_query);

    if ($result->num_rows > 0) {
        echo "<script>alert('Email already exists!'); window.location.href='signup.php';</script>";
    } else {
        // Insert user into customers table
        $query = "INSERT INTO customers (first_name, last_name, contact_no, email, password, account_type) 
                  VALUES ('$first_name', '$last_name', '$contact', '$email', '$hashed_password', 2)";

        if ($conn->query($query)) {
            // Send email with the generated password
            $mail = new PHPMailer(true);  // Passing `true` enables exceptions
            try {
                //Server settings
                $mail->isSMTP();
                $mail->Host = 'smtp.gmail.com'; // Use your SMTP server
                $mail->SMTPAuth = true;
                $mail->Username = 'kennetics1@gmail.com'; // Your email
                $mail->Password = 'bcvn mqgw jxlf gmin';    // Your email password
                $mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
                $mail->Port = 587;

                //Recipients
                $mail->setFrom('kennetics1@gmail.com', 'Sairom Motorshop'); // Sender email and name
                $mail->addAddress($email); // Send to user's email

                // Content
                $mail->isHTML(true);                               
                $mail->Subject = 'Welcome to Sairom Motorshop - Your Generated Password';
                $mail->Body    = "<p>Dear $first_name,</p>
                  <p>Thank you for registering at Sairom Motorshop. We are pleased to inform you that your account has been created successfully.</p>
                  <p>Your autogenerated password is: <strong>$password</strong></p>
                  <p>Please use this password to log in to your account. We recommend changing it to something more memorable after your first login.</p>
                  <p>If you have any questions or need assistance, feel free to contact us.</p>
                  <p>Best regards,<br>Sairom Motorshop Team</p>";

                $mail->send();
                echo "<script>alert('Registration successful! Password sent to your email.'); window.location.href='login-register.php';</script>";
            } catch (Exception $e) {
                echo "<script>alert('Error in sending email: {$mail->ErrorInfo}');</script>";
            }
        } else {
            echo "<script>alert('Error: " . $conn->error . "');</script>";
        }
    }
}
?>
